service: sf-store

custom:
  storesTableName: sf-${self:provider.stage}-stores
  storesTableArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.storesTableName}

provider:
  name: aws
  region: ap-southeast-1 # Singapore
  runtime: go1.x
  memorySize: 192
  stage: ${opt:stage, 'dev'}
  environment:
    STORES_TABLE_NAME: ${self:custom.storesTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - ${self:custom.storesTableArn}

package:
  include:
  - ./bin/**
  exclude:
  - ./**

functions:
  addStore:
    handler: bin/handlers/addStore
    events:
      - http:
          path: stores
          method: post
          cors: true

plugins:


resources:
  Resources:
    StoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.storesTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
