service: sf-store

custom:
  storesTableName: sf-${self:provider.stage}-stores
  storesTableArn:
    Fn::Join:
    - ":"
    - - arn
      - aws
      - dynamodb
      - Ref: AWS::Region
      - Ref: AWS::AccountId
      - table/${self:custom.storesTableName}
  dev:
    region: "ap-southeast-2" # Sydney
  staging:
    region: "ap-southeast-1" # Singapore
  prod:
    region: "ap-southeast-1" # Singapore

provider:
  name: aws
  region: ${self:custom.${self:provider.stage}.region}
  runtime: go1.x
  memorySize: 192
  stage: ${opt:stage, 'dev'}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:provider.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:provider.stage}-ApiGatewayRestApiRootResourceId
  environment:
    STORES_TABLE_NAME: ${self:custom.storesTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - ${self:custom.storesTableArn}

package:
  include:
  - ./bin/**
  exclude:
  - ./**

functions:
  addStore:
    handler: bin/handlers/addStore
    events:
      - http:
          path: /stores
          method: post
          authorizer:
            type: CUSTOM
            authorizerId:
              Fn::ImportValue: ${self:provider.stage}-JwtAuthorizer

  findStore:
    handler: bin/handlers/findStore
    events:
      - http:
          path: /stores/{id}
          method: get
          request:
            parameter:
              paths:
                id: true
          authorizer:
            type: CUSTOM
            authorizerId:
              Fn::ImportValue: ${self:provider.stage}-JwtAuthorizer

resources:
  Resources:
    StoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.storesTableName}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
